### ISSUE TITLE
Kalendar: Nur Termine in der Zukunft auswählen können

### ISSUE THREAD

**Issue by OleKet** [Info-ag/labplaner#30]
Sowohl im Backend, als auch im Frontend nur zulassen, dass solche Auswahltermine von Mentoren beim erstellen eines Events oder nur solche Termine beim Auswählen von möglichen Terminen des Users ausgewählt werden können, die in der Zukunft liegen oder sogar weiter in der Zukunft liegen als x Tage von heute. Oder oder.

**Comment by jnsdrtlf** [comment]
Backend mache ich. Frontend ist ja schon erledigt oder

**Comment by OleKet** [comment]
Richtig.
