### ISSUE TITLE
Handle RegEx-Expressions correctly

### ISSUE THREAD

**Issue by OleKet** [Info-ag/labplaner#37]
Overthink the current RegEx-Expressions and export them to a module, so you can quick-update them.

**Comment by jnsdrtlf** [comment]
what exactly do you mean?

**Comment by OleKet** [comment]
at the momemnt we hard coded every regex expression into the html site and the backend. It would be more comfortable if we would have one file with all regex expression so whe can load them from one this file without need to edit the backend&the frontend

**Comment by OleKet** [comment]
exported regex expressions to config.regex

e.g.:

```
from config.regex import ag_regex
```
